language: cpp

sudo: false

addons:
  apt:
    sources:
      - boost-latest
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
      - lua5.1
      - liblua5.1-0-dev
      - libboost1.55-all-dev
      - libzmq3-dev
      - rubygems

cache:
  - apt

before_script:
  - export CXX="g++-5"
  - gem install rufus-scheduler

script:
  - make -C Build/linux/gmake config=release_x64
  - ruby demo.rb
